# Generated by Django 3.1.8 on 2023-07-05 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Page',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Profile-images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
