# Generated by Django 3.1.8 on 2023-07-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
