# Generated by Django 3.1.8 on 2023-07-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
