# Generated by Django 3.1.8 on 2023-07-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_id', to='home.profile_page'),
        ),
    ]
