# Generated by Django 4.2.4 on 2023-08-13 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiridate', models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 13, 12, 23, 36, 391565, tzinfo=datetime.timezone.utc))),
                ('Profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile_page')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
